projects:
  jcmobile:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
  messageboard:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql-custom/messages.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API-messages.ts
        docsFilePath: src/graphql
  courses:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql-custom/courses.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API-courses.ts
        docsFilePath: src/graphql
  CRM:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql-custom/crm.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API-crm.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
