import { AmplifyAuthCognitoStackTemplate } from "@aws-amplify/cli-extensibility-helper"

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPool.schema = resources.userPool.schema = [
    { name: "phone_number", required: true, mutable: true },
  ]
  resources.userPoolClient.readAttributes = [
    "address",
    "birthdate",
    "email",
    "family_name",
    "middle_name",
    "gender",
    "locale",
    "given_name",
    "name",
    "nickname",
    "phone_number",
    "preferred_username",
    "picture",
    "profile",
    "updated_at",
    "website",
    "zoneinfo",
    "email_verified",
    "phone_number_verified",
    "custom:orgName",
    "custom:isOrg",
  ]
  resources.userPoolClient.writeAttributes = [
    "address",
    "birthdate",
    "middle_name",
    "gender",
    "locale",
    "name",
    "nickname",
    "preferred_username",
    "picture",
    "profile",
    "updated_at",
    "website",
    "zoneinfo",
    "email",
    "family_name",
    "given_name",
    "phone_number",
    "custom:orgName",
    "custom:isOrg",
  ]
  resources.userPoolClientWeb.readAttributes = [
    "address",
    "birthdate",
    "email",
    "family_name",
    "middle_name",
    "gender",
    "locale",
    "given_name",
    "name",
    "nickname",
    "phone_number",
    "preferred_username",
    "picture",
    "profile",
    "updated_at",
    "website",
    "zoneinfo",
    "email_verified",
    "phone_number_verified",
    "custom:orgName",
    "custom:isOrg",
  ]
  resources.userPoolClientWeb.writeAttributes = [
    "address",
    "birthdate",
    "middle_name",
    "gender",
    "locale",
    "name",
    "nickname",
    "preferred_username",
    "picture",
    "profile",
    "updated_at",
    "website",
    "zoneinfo",
    "email",
    "family_name",
    "given_name",
    "phone_number",
    "custom:orgName",
    "custom:isOrg",
  ]
}
