/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type StripePriceInput = {
  prices?: Array< StripePriceDetail | null > | null,
};

export type StripePriceDetail = {
  price?: string | null,
  quantity?: number | null,
};

export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelMessageFilterInput = {
  id?: ModelIDFilterInput | null,
  content?: ModelStringFilterInput | null,
  when?: ModelStringFilterInput | null,
  attachment?: ModelStringFilterInput | null,
  attachmentName?: ModelStringFilterInput | null,
  roomId?: ModelIDFilterInput | null,
  userId?: ModelIDFilterInput | null,
  postingAs?: ModelStringFilterInput | null,
  owner?: ModelStringFilterInput | null,
  and?: Array< ModelMessageFilterInput | null > | null,
  or?: Array< ModelMessageFilterInput | null > | null,
  not?: ModelMessageFilterInput | null,
};

export type ModelIDFilterInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type ModelStringFilterInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export enum PaidState {
  Unknown = "Unknown",
  InProgress = "InProgress",
  NeedsPayment = "NeedsPayment",
  Success = "Success",
}


export type ModelDirectMessageRoomFilterInput = {
  id?: ModelIDFilterInput | null,
  name?: ModelStringFilterInput | null,
  roomType?: ModelStringFilterInput | null,
  and?: Array< ModelDirectMessageRoomFilterInput | null > | null,
  or?: Array< ModelDirectMessageRoomFilterInput | null > | null,
  not?: ModelDirectMessageRoomFilterInput | null,
};

export type ModelIDKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type ModelGroupFilterInput = {
  id?: ModelIDFilterInput | null,
  owner?: ModelStringFilterInput | null,
  ownerOrgID?: ModelIDFilterInput | null,
  type?: ModelStringFilterInput | null,
  name?: ModelStringFilterInput | null,
  description?: ModelStringFilterInput | null,
  memberCount?: ModelIntFilterInput | null,
  image?: ModelStringFilterInput | null,
  time?: ModelStringFilterInput | null,
  lastUpdated?: ModelStringFilterInput | null,
  location?: ModelStringFilterInput | null,
  length?: ModelStringFilterInput | null,
  effort?: ModelStringFilterInput | null,
  cost?: ModelStringFilterInput | null,
  promotionalText?: ModelStringFilterInput | null,
  eventType?: ModelStringFilterInput | null,
  eventUrl?: ModelStringFilterInput | null,
  tz?: ModelStringFilterInput | null,
  isSponsored?: ModelStringFilterInput | null,
  and?: Array< ModelGroupFilterInput | null > | null,
  or?: Array< ModelGroupFilterInput | null > | null,
  not?: ModelGroupFilterInput | null,
};

export type ModelIntFilterInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelDirectMessageUserFilterInput = {
  id?: ModelIDFilterInput | null,
  userName?: ModelStringFilterInput | null,
  userID?: ModelIDFilterInput | null,
  roomID?: ModelIDFilterInput | null,
  and?: Array< ModelDirectMessageUserFilterInput | null > | null,
  or?: Array< ModelDirectMessageUserFilterInput | null > | null,
  not?: ModelDirectMessageUserFilterInput | null,
};

export type PreviewInvoiceMutationVariables = {
  stripeCustomerID?: string | null,
  idempotency?: string | null,
  priceInfo?: StripePriceInput | null,
};

export type PreviewInvoiceMutation = {
  previewInvoice:  {
    __typename: "StripeInvoiceData",
    invoice:  {
      __typename: "StripeInvoice",
      id: string | null,
      object: string | null,
      account_country: string | null,
      account_name: string | null,
      account_tax_ids: string | null,
      amount_due: string | null,
      amount_paid: string | null,
      amount_remaining: string | null,
      application_fee_amount: string | null,
      attempt_count: string | null,
      attempted: string | null,
      auto_advance: string | null,
      billing_reason: string | null,
      charge: string | null,
      collection_method: string | null,
      created: string | null,
      currency: string | null,
      custom_fields: string | null,
      customer: string | null,
      customer_address:  {
        __typename: "StripeAddress",
        city: string | null,
        country: string | null,
        line1: string | null,
        line2: string | null,
        postal_code: string | null,
        state: string | null,
      } | null,
      customer_email: string | null,
      customer_name: string | null,
      customer_phone: string | null,
      customer_shipping: string | null,
      customer_tax_exempt: string | null,
      customer_tax_ids: Array< string | null > | null,
      default_payment_method: string | null,
      default_source: string | null,
      default_tax_rates: Array< string | null > | null,
      description: string | null,
      discount: string | null,
      discounts: Array< string | null > | null,
      due_date: string | null,
      ending_balance: string | null,
      footer: string | null,
      hosted_invoice_url: string | null,
      invoice_pdf: string | null,
      last_finalization_error: string | null,
      lines:  {
        __typename: "StripeLines",
        data:  Array< {
          __typename: "StripeLineData",
          id: string | null,
          object: string | null,
          amount: string | null,
          currency: string | null,
          description: string | null,
          discount_amounts: Array< string | null > | null,
          discountable: string | null,
          discounts: Array< string | null > | null,
          livemode: string | null,
          metadata: string | null,
          period:  {
            __typename: "StripePeriod",
            end: string | null,
            start: string | null,
          } | null,
          price:  {
            __typename: "StripePrice",
            id: string | null,
            object: string | null,
            active: string | null,
            billing_scheme: string | null,
            created: string | null,
            currency: string | null,
            livemode: string | null,
            lookup_key: string | null,
            metadata: string | null,
            nickname: string | null,
            product: string | null,
            recurring:  {
              __typename: "StripeRecurring",
              aggregate_usage: string | null,
              interval: string | null,
              interval_count: string | null,
              usage_type: string | null,
            } | null,
            tiers_mode: string | null,
            transform_quantity: string | null,
            type: string | null,
            unit_amount: string | null,
            unit_amount_decimal: string | null,
          } | null,
          proration: string | null,
          quantity: string | null,
          subscription: string | null,
          subscription_item: string | null,
          tax_amounts: Array< string | null > | null,
          tax_rates: Array< string | null > | null,
          type: string | null,
        } | null > | null,
        has_more: string | null,
        object: string | null,
        url: string | null,
      } | null,
      livemode: string | null,
      metadata: string | null,
      next_payment_attempt: string | null,
      number: string | null,
      paid: string | null,
      payment_intent: string | null,
      period_end: string | null,
      period_start: string | null,
      post_payment_credit_notes_amount: string | null,
      pre_payment_credit_notes_amount: string | null,
      receipt_number: string | null,
      starting_balance: string | null,
      statement_descriptor: string | null,
      status: string | null,
      status_transitions:  {
        __typename: "StripeTransition",
        finalized_at: string | null,
        marked_uncollectible_at: string | null,
        paid_at: string | null,
        voided_at: string | null,
      } | null,
      subscription: string | null,
      subtotal: string | null,
      tax: string | null,
      total: string | null,
      total_discount_amounts: Array< string | null > | null,
      total_tax_amounts: Array< string | null > | null,
      transfer_data: string | null,
      webhooks_delivered_at: string | null,
    } | null,
  } | null,
};

export type MessagesByRoomQueryVariables = {
  roomId?: string | null,
  when?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelMessageFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type MessagesByRoomQuery = {
  messagesByRoom:  {
    __typename: "ModelMessageConnection",
    nextToken: string | null,
    items:  Array< {
      __typename: "Message",
      attachment: string | null,
      attachmentName: string | null,
      author:  {
        __typename: "User",
        aboutMeLong: string | null,
        aboutMeShort: string | null,
        createdAt: string,
        currentRole: string | null,
        currentScope: string | null,
        denomination: string | null,
        email: string | null,
        family_name: string,
        given_name: string,
        hasPaidState: PaidState | null,
        id: string,
        interests: Array< string | null > | null,
        joined: string | null,
        mainUserGroup: string | null,
        numberVolunteers: string | null,
        orgDescription: string | null,
        orgName: string | null,
        orgSize: string | null,
        orgType: string | null,
        owner: string | null,
        phone: string | null,
        personality: string | null,
        pplServed: string | null,
        primaryOrganization: string | null,
        profileState: string | null,
        stripeCustomerID: string | null,
        stripeSubscriptionID: string | null,
        sundayAttendance: string | null,
        updatedAt: string,
      } | null,
      content: string,
      createdAt: string,
      id: string,
      owner: string | null,
      postingAs: string | null,
      roomId: string | null,
      updatedAt: string,
      userId: string | null,
      when: string,
      replies:  {
        __typename: "ModelReplyConnection",
        items:  Array< {
          __typename: "Reply",
          attachment: string | null,
          attachmentName: string | null,
          author:  {
            __typename: "User",
            aboutMeLong: string | null,
            aboutMeShort: string | null,
            createdAt: string,
            currentRole: string | null,
            currentScope: string | null,
            denomination: string | null,
            email: string | null,
            family_name: string,
            given_name: string,
            hasPaidState: PaidState | null,
            id: string,
            interests: Array< string | null > | null,
            joined: string | null,
            mainUserGroup: string | null,
            numberVolunteers: string | null,
            orgDescription: string | null,
            orgName: string | null,
            orgSize: string | null,
            orgType: string | null,
            owner: string | null,
            personality: string | null,
            phone: string | null,
            pplServed: string | null,
            primaryOrganization: string | null,
            updatedAt: string,
            sundayAttendance: string | null,
            stripeCustomerID: string | null,
            stripeSubscriptionID: string | null,
            profileState: string | null,
          } | null,
          content: string,
          createdAt: string,
          id: string,
          messageId: string,
          parentReplyId: string,
          updatedAt: string,
          userId: string,
          when: string,
        } | null > | null,
      } | null,
    } | null > | null,
  } | null,
};

export type ListDirectMessageRoomsQueryVariables = {
  filter?: ModelDirectMessageRoomFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListDirectMessageRoomsQuery = {
  listDirectMessageRooms:  {
    __typename: "ModelDirectMessageRoomConnection",
    items:  Array< {
      __typename: "DirectMessageRoom",
      id: string,
      name: string | null,
      roomType: string | null,
      messageUsers:  {
        __typename: "ModelDirectMessageUserConnection",
        items:  Array< {
          __typename: "DirectMessageUser",
          id: string,
          userName: string | null,
          userID: string,
          roomID: string,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken: string | null,
      } | null,
      directMessage:  {
        __typename: "ModelDirectMessageConnection",
        items:  Array< {
          __typename: "DirectMessage",
          id: string,
          content: string | null,
          attachment: string | null,
          attachmentName: string | null,
          when: string,
          recipients: Array< string | null >,
          userId: string,
          messageRoomID: string,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    mainUserGroup: string | null,
    hasPaidState: PaidState | null,
    profileState: string | null,
    billingAddress:  {
      __typename: "Address",
      city: string | null,
      country: string | null,
      line1: string | null,
      line2: string | null,
      postal_code: string | null,
      state: string | null,
    } | null,
    location:  {
      __typename: "LatLong",
      latitude: string | null,
      longitude: string | null,
      geocodeFull: string | null,
      geocodeCity: string | null,
      geocodeRegion: string | null,
      randomLatitude: string | null,
      randomLongitude: string | null,
    } | null,
    profileImage:  {
      __typename: "Image",
      userId: string | null,
      filenameSmall: string | null,
      filenameMedium: string | null,
      filenameLarge: string | null,
      filenameUpload: string | null,
    } | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: Array< string | null > | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    denomination: string | null,
    pplServed: string | null,
    sundayAttendance: string | null,
    numberVolunteers: string | null,
    orgDescription: string | null,
    joined: string | null,
    primaryOrganization: string | null,
    organizations:  {
      __typename: "ModelOrganizationMemberConnection",
      items:  Array< {
        __typename: "OrganizationMember",
        id: string,
        userRole: string,
        userId: string,
        organizationId: string,
        organizationName: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    owns:  {
      __typename: "ModelGroupConnection",
      items:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        ownerOrgID: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
        promotionalText: string | null,
        eventType: string | null,
        eventUrl: string | null,
        tz: string | null,
        isSponsored: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    groups:  {
      __typename: "ModelGroupMemberConnection",
      items:  Array< {
        __typename: "GroupMember",
        id: string,
        groupID: string | null,
        userID: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    alertConfig:  {
      __typename: "AlertConfig",
      emailDirectMessage: string | null,
      emailGroupMessage: string | null,
      emailEventMessage: string | null,
      emailOrgMessage: string | null,
      emailResourceMessage: string | null,
      emailCourseMessage: string | null,
      emailPromotions: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetCourseInfoQueryVariables = {
  id: string,
};

export type GetCourseInfoQuery = {
  getCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    designedBy: string | null,
    summary: string | null,
    sylabusAttachmentName: string | null,
    sylabusAttachment: string | null,
    backOfficeStaff:  {
      __typename: "ModelCourseBackOfficeStaffConnection",
      items:  Array< {
        __typename: "CourseBackOfficeStaff",
        id: string,
        courseInfoID: string | null,
        userID: string | null,
        user:  {
          __typename: "User",
          id: string,
          given_name: string,
          family_name: string,
          email: string | null,
          phone: string | null,
          owner: string | null,
          mainUserGroup: string | null,
          hasPaidState: PaidState | null,
          profileState: string | null,
          billingAddress:  {
            __typename: "Address",
            city: string | null,
            country: string | null,
            line1: string | null,
            line2: string | null,
            postal_code: string | null,
            state: string | null,
          } | null,
          location:  {
            __typename: "LatLong",
            latitude: string | null,
            longitude: string | null,
            geocodeFull: string | null,
            geocodeCity: string | null,
            geocodeRegion: string | null,
            randomLatitude: string | null,
            randomLongitude: string | null,
          } | null,
          profileImage:  {
            __typename: "Image",
            userId: string | null,
            filenameSmall: string | null,
            filenameMedium: string | null,
            filenameLarge: string | null,
            filenameUpload: string | null,
          } | null,
          aboutMeShort: string | null,
          aboutMeLong: string | null,
          interests: Array< string | null > | null,
          currentRole: string | null,
          currentScope: string | null,
          personality: string | null,
          orgName: string | null,
          orgType: string | null,
          orgSize: string | null,
          denomination: string | null,
          pplServed: string | null,
          sundayAttendance: string | null,
          numberVolunteers: string | null,
          orgDescription: string | null,
          joined: string | null,
          primaryOrganization: string | null,
          organizations:  {
            __typename: "ModelOrganizationMemberConnection",
            nextToken: string | null,
          } | null,
          owns:  {
            __typename: "ModelGroupConnection",
            nextToken: string | null,
          } | null,
          groups:  {
            __typename: "ModelGroupMemberConnection",
            nextToken: string | null,
          } | null,
          messages:  {
            __typename: "ModelMessageConnection",
            nextToken: string | null,
          } | null,
          directMessages:  {
            __typename: "ModelDirectMessageConnection",
            nextToken: string | null,
          } | null,
          alertConfig:  {
            __typename: "AlertConfig",
            emailDirectMessage: string | null,
            emailGroupMessage: string | null,
            emailEventMessage: string | null,
            emailOrgMessage: string | null,
            emailResourceMessage: string | null,
            emailCourseMessage: string | null,
            emailPromotions: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
    } | null,
    instructors:  {
      __typename: "ModelCourseInstructorsConnection",
      items:  Array< {
        __typename: "CourseInstructors",
        id: string,
        courseInfoID: string | null,
        userID: string | null,
        user:  {
          __typename: "User",
          id: string,
          given_name: string,
          family_name: string,
          email: string | null,
          phone: string | null,
          owner: string | null,
          mainUserGroup: string | null,
          hasPaidState: PaidState | null,
          profileState: string | null,
          billingAddress:  {
            __typename: "Address",
            city: string | null,
            country: string | null,
            line1: string | null,
            line2: string | null,
            postal_code: string | null,
            state: string | null,
          } | null,
          location:  {
            __typename: "LatLong",
            latitude: string | null,
            longitude: string | null,
            geocodeFull: string | null,
            geocodeCity: string | null,
            geocodeRegion: string | null,
            randomLatitude: string | null,
            randomLongitude: string | null,
          } | null,
          profileImage:  {
            __typename: "Image",
            userId: string | null,
            filenameSmall: string | null,
            filenameMedium: string | null,
            filenameLarge: string | null,
            filenameUpload: string | null,
          } | null,
          aboutMeShort: string | null,
          aboutMeLong: string | null,
          interests: Array< string | null > | null,
          currentRole: string | null,
          currentScope: string | null,
          personality: string | null,
          orgName: string | null,
          orgType: string | null,
          orgSize: string | null,
          denomination: string | null,
          pplServed: string | null,
          sundayAttendance: string | null,
          numberVolunteers: string | null,
          orgDescription: string | null,
          joined: string | null,
          primaryOrganization: string | null,
          organizations:  {
            __typename: "ModelOrganizationMemberConnection",
            nextToken: string | null,
          } | null,
          owns:  {
            __typename: "ModelGroupConnection",
            nextToken: string | null,
          } | null,
          groups:  {
            __typename: "ModelGroupMemberConnection",
            nextToken: string | null,
          } | null,
          messages:  {
            __typename: "ModelMessageConnection",
            nextToken: string | null,
          } | null,
          directMessages:  {
            __typename: "ModelDirectMessageConnection",
            nextToken: string | null,
          } | null,
          alertConfig:  {
            __typename: "AlertConfig",
            emailDirectMessage: string | null,
            emailGroupMessage: string | null,
            emailEventMessage: string | null,
            emailOrgMessage: string | null,
            emailResourceMessage: string | null,
            emailCourseMessage: string | null,
            emailPromotions: string | null,
          } | null,
          createdAt: string,
          updatedAt: string,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
    } | null,
    courseWeeks:  {
      __typename: "ModelCourseWeekConnection",
      items:  Array< {
        __typename: "CourseWeek",
        id: string,
        week: string | null,
        date: string | null,
        tz: string | null,
        name: string | null,
        title: string | null,
        leader: string | null,
        lessons:  {
          __typename: "ModelCourseLessonConnection",
          items:  Array< {
            __typename: "CourseLesson",
            id: string,
            lesson: string | null,
            lessonType: string | null,
            wordCount: string | null,
            courseLessonResponseId: string | null,
            zoomUrl: string | null,
            zoomRecording: string | null,
            name: string | null,
            time: string | null,
            tz: string | null,
            duration: string | null,
            description: string | null,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    subTitle: string | null,
    introduction: string | null,
    triads:  {
      __typename: "ModelCourseTriadsConnection",
      items:  Array< {
        __typename: "CourseTriads",
        id: string,
        courseInfoID: string | null,
        coaches:  {
          __typename: "ModelCourseTriadCoachesConnection",
          items:  Array< {
            __typename: "CourseTriadCoaches",
            id: string,
            triadID: string | null,
            userID: string | null,
            user:  {
              __typename: "User",
              id: string,
              given_name: string,
              family_name: string,
              email: string | null,
              phone: string | null,
              owner: string | null,
              profileImage:  {
                __typename: "Image",
                userId: string | null,
                filenameSmall: string | null,
                filenameMedium: string | null,
                filenameLarge: string | null,
                filenameUpload: string | null,
              } | null,
            } | null,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken: string | null,
        } | null,
        users:  {
          __typename: "ModelCourseTriadUsersConnection",
          items:  Array< {
            __typename: "CourseTriadUsers",
            id: string,
            triadID: string | null,
            userID: string | null,
            user:  {
              __typename: "User",
              id: string,
              given_name: string,
              family_name: string,
              email: string | null,
              phone: string | null,
              owner: string | null,
              profileImage:  {
                __typename: "Image",
                userId: string | null,
                filenameSmall: string | null,
                filenameMedium: string | null,
                filenameLarge: string | null,
                filenameUpload: string | null,
              } | null,
            } | null,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetDirectMessageUserQueryVariables = {
  id: string,
};

export type GetDirectMessageUserQuery = {
  getDirectMessageUser:  {
    __typename: "DirectMessageUser",
    id: string,
    userID: string,
    user:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      mainUserGroup: string | null,
      hasPaidState: PaidState | null,
      profileState: string | null,
      billingAddress:  {
        __typename: "Address",
        city: string | null,
        country: string | null,
        line1: string | null,
        line2: string | null,
        postal_code: string | null,
        state: string | null,
      } | null,
      location:  {
        __typename: "LatLong",
        latitude: string | null,
        longitude: string | null,
        geocodeFull: string | null,
        geocodeCity: string | null,
        geocodeRegion: string | null,
      } | null,
      profileImage:  {
        __typename: "Image",
        userId: string | null,
        filenameSmall: string | null,
        filenameMedium: string | null,
        filenameLarge: string | null,
        filenameUpload: string | null,
      } | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: Array< string | null > | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
      joined: string | null,
      primaryOrganization: string | null,
      owns:  {
        __typename: "ModelGroupConnection",
        nextToken: string | null,
      } | null,
      groups:  {
        __typename: "ModelGroupMemberConnection",
        nextToken: string | null,
      } | null,
      messages:  {
        __typename: "ModelMessageConnection",
        nextToken: string | null,
      } | null,
      directMessages:  {
        __typename: "ModelDirectMessageConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    roomID: string,
    room:  {
      __typename: "DirectMessageRoom",
      id: string,
      name: string | null,
      roomType: string | null,
      messageUsers:  {
        __typename: "ModelDirectMessageUserConnection",
        items:  Array< {
          __typename: "DirectMessageUser",
          id: string,
          userName: string | null,
          userID: string,
          roomID: string,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken: string | null,
      } | null,
      directMessage:  {
        __typename: "ModelDirectMessageConnection",
        items:  Array< {
          __typename: "DirectMessage",
          id: string,
          content: string | null,
          when: string,
          messageRoomID: string,
          createdAt: string,
          updatedAt: string,
        } | null > | null,
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetGroupQueryVariables = {
  id: string,
};

export type GetGroupQuery = {
  getGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
  } | null,
};

export type GroupByTypeQueryVariables = {
  type?: string | null,
  id?: ModelIDKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelGroupFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type GroupByTypeQuery = {
  groupByType:  {
    __typename: "ModelGroupConnection",
    items:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      ownerUser:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
      } | null,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      locationLatLong:  {
        __typename: "LatLong",
        latitude: string | null,
        longitude: string | null,
        geocodeFull: string | null,
        geocodeCity: string | null,
        geocodeRegion: string | null,
      } | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      eventType: string | null,
      eventUrl: string | null,
      tz: string | null,
      isSponsored: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type getOrganizationQueryVariables = {
  id: string,
};

export type getOrganizationQuery = {
  getOrganization:  {
    __typename: "Organization",
    id: string,
    profileImage:  {
      __typename: "Image",
      userId: string | null,
      filenameSmall: string | null,
      filenameMedium: string | null,
      filenameLarge: string | null,
      filenameUpload: string | null,
    } | null,
  } | null,
};

export type ListDirectMessageUsersQueryVariables = {
  filter?: ModelDirectMessageUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListDirectMessageUsersQuery = {
  listDirectMessageUsers:  {
    __typename: "ModelDirectMessageUserConnection",
    items:  Array< {
      __typename: "DirectMessageUser",
      id: string,
      userID: string,
      user:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: PaidState | null,
        profileState: string | null,
        billingAddress:  {
          __typename: "Address",
          city: string | null,
          country: string | null,
          line1: string | null,
          line2: string | null,
          postal_code: string | null,
          state: string | null,
        } | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: Array< string | null > | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
        joined: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      roomID: string,
      room:  {
        __typename: "DirectMessageRoom",
        id: string,
        name: string | null,
        roomType: string | null,
        messageUsers:  {
          __typename: "ModelDirectMessageUserConnection",
          items:  Array< {
            __typename: "DirectMessageUser",
            id: string,
            userName: string | null,
            userID: string,
            roomID: string,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken: string | null,
        } | null,
        directMessage:  {
          __typename: "ModelDirectMessageConnection",
          items:  Array< {
            __typename: "DirectMessage",
            id: string,
            content: string | null,
            when: string,
            messageRoomID: string,
            createdAt: string,
            updatedAt: string,
          } | null > | null,
          nextToken: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};
