/* tslint:disable */
//  This file was automatically generated and should not be edited.

export type CreateUserInput = {
  id?: string | null,
  given_name: string,
  family_name: string,
  email?: string | null,
  phone?: string | null,
  owner?: string | null,
  hasPaidState?: string | null,
  address?: string | null,
  city?: string | null,
  province?: string | null,
  postalCode?: string | null,
  country?: string | null,
  profileImage?: string | null,
  aboutMeShort?: string | null,
  aboutMeLong?: string | null,
  interests?: string | null,
  currentRole?: string | null,
  currentScope?: string | null,
  personality?: string | null,
  orgName?: string | null,
  orgType?: string | null,
  orgSize?: string | null,
  orgDescription?: string | null,
};

export type UpdateUserInput = {
  id: string,
  given_name?: string | null,
  family_name?: string | null,
  email?: string | null,
  phone?: string | null,
  owner?: string | null,
  hasPaidState?: string | null,
  address?: string | null,
  city?: string | null,
  province?: string | null,
  postalCode?: string | null,
  country?: string | null,
  profileImage?: string | null,
  aboutMeShort?: string | null,
  aboutMeLong?: string | null,
  interests?: string | null,
  currentRole?: string | null,
  currentScope?: string | null,
  personality?: string | null,
  orgName?: string | null,
  orgType?: string | null,
  orgSize?: string | null,
  orgDescription?: string | null,
};

export type DeleteUserInput = {
  id?: string | null,
};

export type CreateGroupInput = {
  id?: string | null,
  owner: string,
  type: string,
  name: string,
  description: string,
  memberCount?: number | null,
  image: string,
  time?: string | null,
  lastUpdated?: string | null,
  location?: string | null,
  length?: string | null,
  effort?: string | null,
  cost?: string | null,
};

export type UpdateGroupInput = {
  id: string,
  owner?: string | null,
  type?: string | null,
  name?: string | null,
  description?: string | null,
  memberCount?: number | null,
  image?: string | null,
  time?: string | null,
  lastUpdated?: string | null,
  location?: string | null,
  length?: string | null,
  effort?: string | null,
  cost?: string | null,
};

export type DeleteGroupInput = {
  id?: string | null,
};

export type CreateCourseInfoInput = {
  id?: string | null,
  summary?: string | null,
  course?: Array< CourseWeekInput | null > | null,
};

export type CourseWeekInput = {
  week?: number | null,
  name?: string | null,
  sections?: Array< CourseSectionInput | null > | null,
};

export type CourseSectionInput = {
  section?: number | null,
  name?: string | null,
};

export type UpdateCourseInfoInput = {
  id: string,
  summary?: string | null,
  course?: Array< CourseWeekInput | null > | null,
};

export type DeleteCourseInfoInput = {
  id?: string | null,
};

export type ModelUserFilterInput = {
  id?: ModelIDFilterInput | null,
  given_name?: ModelStringFilterInput | null,
  family_name?: ModelStringFilterInput | null,
  email?: ModelStringFilterInput | null,
  phone?: ModelStringFilterInput | null,
  owner?: ModelStringFilterInput | null,
  hasPaidState?: ModelStringFilterInput | null,
  address?: ModelStringFilterInput | null,
  city?: ModelStringFilterInput | null,
  province?: ModelStringFilterInput | null,
  postalCode?: ModelStringFilterInput | null,
  country?: ModelStringFilterInput | null,
  profileImage?: ModelStringFilterInput | null,
  aboutMeShort?: ModelStringFilterInput | null,
  aboutMeLong?: ModelStringFilterInput | null,
  interests?: ModelStringFilterInput | null,
  currentRole?: ModelStringFilterInput | null,
  currentScope?: ModelStringFilterInput | null,
  personality?: ModelStringFilterInput | null,
  orgName?: ModelStringFilterInput | null,
  orgType?: ModelStringFilterInput | null,
  orgSize?: ModelStringFilterInput | null,
  orgDescription?: ModelStringFilterInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type ModelIDFilterInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type ModelStringFilterInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type ModelGroupFilterInput = {
  id?: ModelIDFilterInput | null,
  owner?: ModelStringFilterInput | null,
  type?: ModelStringFilterInput | null,
  name?: ModelStringFilterInput | null,
  description?: ModelStringFilterInput | null,
  memberCount?: ModelIntFilterInput | null,
  image?: ModelStringFilterInput | null,
  time?: ModelStringFilterInput | null,
  lastUpdated?: ModelStringFilterInput | null,
  location?: ModelStringFilterInput | null,
  length?: ModelStringFilterInput | null,
  effort?: ModelStringFilterInput | null,
  cost?: ModelStringFilterInput | null,
  and?: Array< ModelGroupFilterInput | null > | null,
  or?: Array< ModelGroupFilterInput | null > | null,
  not?: ModelGroupFilterInput | null,
};

export type ModelIntFilterInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  contains?: number | null,
  notContains?: number | null,
  between?: Array< number | null > | null,
};

export type ModelCourseInfoFilterInput = {
  id?: ModelIDFilterInput | null,
  summary?: ModelStringFilterInput | null,
  and?: Array< ModelCourseInfoFilterInput | null > | null,
  or?: Array< ModelCourseInfoFilterInput | null > | null,
  not?: ModelCourseInfoFilterInput | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
};

export type CreateUserMutation = {
  createUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
};

export type UpdateUserMutation = {
  updateUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type DeleteUserMutationVariables = {
  input: DeleteUserInput,
};

export type DeleteUserMutation = {
  deleteUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type CreateGroupMutationVariables = {
  input: CreateGroupInput,
};

export type CreateGroupMutation = {
  createGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type UpdateGroupMutationVariables = {
  input: UpdateGroupInput,
};

export type UpdateGroupMutation = {
  updateGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type DeleteGroupMutationVariables = {
  input: DeleteGroupInput,
};

export type DeleteGroupMutation = {
  deleteGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type CreateCourseInfoMutationVariables = {
  input: CreateCourseInfoInput,
};

export type CreateCourseInfoMutation = {
  createCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type UpdateCourseInfoMutationVariables = {
  input: UpdateCourseInfoInput,
};

export type UpdateCourseInfoMutation = {
  updateCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type DeleteCourseInfoMutationVariables = {
  input: DeleteCourseInfoInput,
};

export type DeleteCourseInfoMutation = {
  deleteCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetGroupQueryVariables = {
  id: string,
};

export type GetGroupQuery = {
  getGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type ListGroupsQueryVariables = {
  filter?: ModelGroupFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListGroupsQuery = {
  listGroups:  {
    __typename: "ModelGroupConnection",
    items:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetCourseInfoQueryVariables = {
  id: string,
};

export type GetCourseInfoQuery = {
  getCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type ListCourseInfosQueryVariables = {
  filter?: ModelCourseInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCourseInfosQuery = {
  listCourseInfos:  {
    __typename: "ModelCourseInfoConnection",
    items:  Array< {
      __typename: "CourseInfo",
      id: string,
      summary: string | null,
      course:  Array< {
        __typename: "CourseWeek",
        week: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type OnCreateUserSubscriptionVariables = {
  owner: string,
};

export type OnCreateUserSubscription = {
  onCreateUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type OnUpdateUserSubscriptionVariables = {
  owner: string,
};

export type OnUpdateUserSubscription = {
  onUpdateUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type OnDeleteUserSubscriptionVariables = {
  owner: string,
};

export type OnDeleteUserSubscription = {
  onDeleteUser:  {
    __typename: "User",
    id: string,
    given_name: string,
    family_name: string,
    email: string | null,
    phone: string | null,
    owner: string | null,
    hasPaidState: string | null,
    address: string | null,
    city: string | null,
    province: string | null,
    postalCode: string | null,
    country: string | null,
    profileImage: string | null,
    aboutMeShort: string | null,
    aboutMeLong: string | null,
    interests: string | null,
    currentRole: string | null,
    currentScope: string | null,
    personality: string | null,
    orgName: string | null,
    orgType: string | null,
    orgSize: string | null,
    orgDescription: string | null,
  } | null,
};

export type OnCreateGroupSubscriptionVariables = {
  owner: string,
};

export type OnCreateGroupSubscription = {
  onCreateGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type OnUpdateGroupSubscriptionVariables = {
  owner: string,
};

export type OnUpdateGroupSubscription = {
  onUpdateGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type OnDeleteGroupSubscriptionVariables = {
  owner: string,
};

export type OnDeleteGroupSubscription = {
  onDeleteGroup:  {
    __typename: "Group",
    id: string,
    owner: string,
    type: string,
    name: string,
    description: string,
    memberCount: number | null,
    members:  {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null,
    image: string,
    time: string | null,
    lastUpdated: string | null,
    location: string | null,
    length: string | null,
    effort: string | null,
    cost: string | null,
    organizerGroup:  Array< {
      __typename: "Group",
      id: string,
      owner: string,
      type: string,
      name: string,
      description: string,
      memberCount: number | null,
      members:  {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null,
      image: string,
      time: string | null,
      lastUpdated: string | null,
      location: string | null,
      length: string | null,
      effort: string | null,
      cost: string | null,
      organizerGroup:  Array< {
        __typename: "Group",
        id: string,
        owner: string,
        type: string,
        name: string,
        description: string,
        memberCount: number | null,
        image: string,
        time: string | null,
        lastUpdated: string | null,
        location: string | null,
        length: string | null,
        effort: string | null,
        cost: string | null,
      } | null > | null,
      organizerUser:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
      instructors:  Array< {
        __typename: "User",
        id: string,
        given_name: string,
        family_name: string,
        email: string | null,
        phone: string | null,
        owner: string | null,
        hasPaidState: string | null,
        address: string | null,
        city: string | null,
        province: string | null,
        postalCode: string | null,
        country: string | null,
        profileImage: string | null,
        aboutMeShort: string | null,
        aboutMeLong: string | null,
        interests: string | null,
        currentRole: string | null,
        currentScope: string | null,
        personality: string | null,
        orgName: string | null,
        orgType: string | null,
        orgSize: string | null,
        orgDescription: string | null,
      } | null > | null,
    } | null > | null,
    organizerUser:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
    instructors:  Array< {
      __typename: "User",
      id: string,
      given_name: string,
      family_name: string,
      email: string | null,
      phone: string | null,
      owner: string | null,
      hasPaidState: string | null,
      address: string | null,
      city: string | null,
      province: string | null,
      postalCode: string | null,
      country: string | null,
      profileImage: string | null,
      aboutMeShort: string | null,
      aboutMeLong: string | null,
      interests: string | null,
      currentRole: string | null,
      currentScope: string | null,
      personality: string | null,
      orgName: string | null,
      orgType: string | null,
      orgSize: string | null,
      orgDescription: string | null,
    } | null > | null,
  } | null,
};

export type OnCreateCourseInfoSubscriptionVariables = {
  owner: string,
};

export type OnCreateCourseInfoSubscription = {
  onCreateCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type OnUpdateCourseInfoSubscriptionVariables = {
  owner: string,
};

export type OnUpdateCourseInfoSubscription = {
  onUpdateCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type OnDeleteCourseInfoSubscriptionVariables = {
  owner: string,
};

export type OnDeleteCourseInfoSubscription = {
  onDeleteCourseInfo:  {
    __typename: "CourseInfo",
    id: string,
    summary: string | null,
    course:  Array< {
      __typename: "CourseWeek",
      week: number | null,
      name: string | null,
      sections:  Array< {
        __typename: "CourseSection",
        section: number | null,
        name: string | null,
      } | null > | null,
    } | null > | null,
  } | null,
};
