// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9de34c5d-3a9b-4032-a836-09d55f2e95d1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_V7pdDNjW2",
    "aws_user_pools_web_client_id": "3vcsprpflitom2se5un0m6bqm7",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://chx7bfj4sbgtfoam6myzmyhafu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "heeetingouse-20190312104205-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://heeetingouse-20190312104205-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_mobile_analytics_app_id": "9228df96ac634f629edc870f3e1b2fd5",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
