/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7b6acfbf-d55c-46e9-a0de-d3bf264f8fca",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fe30GuOOt",
    "aws_user_pools_web_client_id": "68v5dgb5s96v9lf87cjfpeqmn9",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://uaixja4mvfe37gwyffy4qwez4m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-56sxbbwj5rgq7cygccrxkyldfu",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://y214sfi50m.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_mobile_analytics_app_id": "26ed2c1ca2164bad96971e89ce704143",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "jc-mobile-20190818234527-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3uxxql9osbe4a.cloudfront.net",
    "aws_user_files_s3_bucket": "jc-profile20190809190418-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
